services:
  redis:
    image: redis:latest
    ports:
      - "6380:6379"   # Only if you want to access Redis from your host

  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    depends_on:
      - redis
